// NEXT.JS
import type { Metadata } from "next";
// STYLES
import "./globals.css";
import Logo from "./components/Logo";
import Dropdown from "./components/Dropdown";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFile, faFolderOpen } from "@fortawesome/free-solid-svg-icons";
import Icons from "./components/Icons";
import ApplicationHeader from "./containers/ApplicationHeader";
import ApplicationSidebar from "./containers/ApplicationSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white min-h-dhv grid grid-rows-[60px_1fr] gap-x-6">
        <ApplicationHeader />
        <main className="w-full h-page grid grid-cols-[400px_1fr]">
          <ApplicationSidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
